In [1]:
import numpy as np

## <b>Table of contents</b>

<ul>
    <li>Jupyter and Colab Notebooks</li><br>
    <li>Python</li><br>
    <li>Numpy</li><br>
    <li>Scipy</li><br>
    <li>Matplotlib</li>
</ul>

In [7]:
!python3 --version

Python 3.7.6


python does not have unary increment(x++) or decrement(x--) operators.

In [8]:
x = 2
y = 3
print(x and y)

3


In [9]:
print(x or y)

2


In [10]:
print(x != y)

True


In [16]:
# logical XOR

x = 3
y = 5
print(x != y)

False


In [17]:
name = "Min Hyeok"
language = "Kor"

can_speak = "My name is %s and my main language is %s %d" %(name, language, 5)

In [18]:
can_speak

'My name is Min Hyeok and my main language is Kor 5'

In [19]:
s = "hello"
s.capitalize()

'Hello'

In [20]:
s

'hello'

In [21]:
s.upper()

'HELLO'

In [22]:
s

'hello'

In [23]:
s.rjust(7)

'  hello'

In [24]:
s

'hello'

In [25]:
s.center(7)

' hello '

In [26]:
s

'hello'

In [27]:
print("   world".strip())

world


### Dictionaries

In [28]:
d = {"cat" : "cute", "dog" :  "furry"}
print(d["cat"])

cute


In [29]:
d["fish"] = "wet"

In [30]:
d

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [31]:
del d["fish"]

In [32]:
d

{'cat': 'cute', 'dog': 'furry'}

In [35]:
print(d.get('monkey', "N/A"))
print(d.get("dog", "N/A")) # get(A, B) if key in d print A otherwise B

N/A
furry


### Dictionary comprehensions

In [36]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x : x**2 for x in nums if x % 2 == 0}

In [37]:
even_num_to_square

{0: 0, 2: 4, 4: 16}

### Sets

In [39]:
animals = {"cat", "dog"}

In [40]:
"cat" in animals

True

In [41]:
print(len(animals))

2


In [43]:
for idx, animal in enumerate(animals):
    print("%d %s"%(idx + 1, animal))

1 dog
2 cat


### Set comprehensions

In [44]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}

### Classes

In [48]:
class Greeter(object):
    
    def __init__(self, name):
        self.name = name
    
    def greet(self, loud = False):
        if loud:
            print("Hello, %s!" % self.name.upper())
        else:
            print("Hello, %s" % self.name)
        

In [49]:
g = Greeter("Seol")

In [50]:
g.greet()

Hello, Seol


In [51]:
g.greet(loud = True)

Hello, SEOL!


# Numpy

In [53]:
a = np.zeros((2, 2))
print(a)
print(a.ndim)

[[0. 0.]
 [0. 0.]]
2


In [54]:
b = np.ones((1, 2))
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [55]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
print(d.ndim)

2


In [58]:
e = np.random.random((2, 2))
print(e)

[[0.41008286 0.632377  ]
 [0.34237688 0.55963912]]


In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
row_r1 = a[1, :]

row_r1

array([5, 6, 7, 8])

In [63]:
row_r2 = a[2, :]

row_r2

array([ 9, 10, 11, 12])

In [64]:
row_r1.ndim # row 추출하면 차원 감소하고, shape도 하나로 바뀜

1

In [65]:
row_r1.shape

(4,)

In [66]:
mat_a = a[1:3, 2:4]

In [67]:
mat_a.ndim

2

In [68]:
mat_a.shape

(2, 2)

In [70]:
col_r1 = a[:, 0]

col_r1

array([1, 5, 9])

In [71]:
col_r1.shape

(3,)

### some useful way

In [74]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a, a.ndim)
print()
b = np.array([0, 2, 0, 1])
print(b, b.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 2

[0 2 0 1] 1


In [76]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [77]:
a[np.arange(4), b] += 10

In [78]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

### boolean indexing

In [79]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a[a>2]

array([3, 4, 5, 6])

In [80]:
bool_idx = a>2

In [81]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

### Array math

In [82]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

In [83]:
print(x)

[[1. 2.]
 [3. 4.]]


In [84]:
print(y)

[[5. 6.]
 [7. 8.]]
